image: node:16

stages:
  - analyze

variables:
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  GIT_DEPTH: "0"

sonarcloud:
  stage: analyze
  script:
    - npm install
    - npx sonar-scanner \
      -Dsonar.projectKey=hebakarim_goToCode \
      -Dsonar.organization=sonar-project-properties \
      -Dsonar.host.url=https://sonarcloud.io \
      -Dsonar.login=$SONAR_TOKEN
  only:
    - main
